### ISSUE TITLE
Kill is quite strong...

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#7]
sophomorix uses "kill" (the verb) a lot. Personally I think that "remove" is the better term, a least for everything that is output to the user (e.g. `The following users can be killed` does not sound like linuxmuster._nett_). When adding new devices there are many occurrences of "kill", too.

This is a just suggestion... not a major issue.

**Comment by jeffbeck** [comment]
kill was chosen a long time ago, because then the new feature of sophomorix was, that users are not permanently removed, but just disabled (another word that shouldn't be used  with user, but only with their login) as a first step. 
So killing meant: permenently remove the user from the system with only traces of her in the log files. No way to recover the user. No way to retrieve her personal data.

Today I would choose another term (delete would be my favourite), but the 'kill' is  very prominent in the code (variable names, ..., grep finds 800 results). So I will leave it for now. If there is enought time before the LMN7 release, I will change it.

**Comment by zefanja** [comment]
Thanks @jeffbeck !
