### ISSUE TITLE
Sophomorix-newfile does not create an error json output

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#74]
Having a maleformed csv file:

more sortedCSV.csv                                                                                                                                                                                                  `
01.01.2008;01.01.2008;01.01.2008;01.01.2008;
01.01.2008;01.01.2008;01.01.2008;01.01.2008;
01.01.2008;01.01.2008;01.01.2008;01.01.2008;
01.01.2008;01.01.2008;01.01.2008;01.01.2008;
`
running: 
`sophomorix-newfile /tmp/sortedCSV.csv --name students.csv -j `

```
ENCODING IS unknown (FALSE, /tmp/sortedCSV.csv)
   * New file:         sortedCSV.csv  (Renamed to: students.csv)
     * Newfile_abs:    /tmp/sortedCSV.csv
   * Target file:      /etc/linuxmuster/sophomorix/default-school/students.csv
   * Target school:    default-school
   * Log new file to:  /var/log/sophomorix/newfiles/default-school/2019-05-28_16-42-03_students.csv.orig
     * filtered:       /var/log/sophomorix/newfiles/default-school/2019-05-28_16-42-03_students.csv.filter
     * utf8:           /var/log/sophomorix/newfiles/default-school/2019-05-28_16-42-03_students.csv.filter.utf8
   * Log old file to:  /var/log/sophomorix/etcfiles/default-school/2019-05-28_16-42-03_students.csv
   * Filterscript:  ---

ERROR: Encoding could not be determined for this file:
   /tmp/sortedCSV.csv

NOT doing anything!

For hints what went wrong use:
  sophomorix-check -vv --analyze /tmp/sortedCSV.csv


```
provides no json output at all

**Comment by jeffbeck** [comment]
In the meantime, there is an json output for this file.

Since it is easily identified as being semicolon-separated and containing no Umlaut chars, ist is a valid pure ASCII file and (by developer convention) treated by sophomorix as UTF8-encoded.

so the json output is: 
/usr/sbin/sophomorix-newfile terminated regularly
and Error output

In the next step (sophomorix-check) sophomorix analyzes the content of the fields and discovers the nonsense in this file
